export {
  faEye,
  faEdit,
  faTrash,
  faChevronRight,
  faCheck,
  faQuoteRight,
  faDog,
  faHome,
  faMoneyCheckAlt,
  faBriefcaseMedical,
  faPhoneSquare,
  faCalendarAlt,
  faMapMarkerAlt,
} from '@fortawesome/free-solid-svg-icons'
